### ISSUE TITLE
Question: usage example

### ISSUE THREAD

**Issue by josephtaylor** [helius-labs/atlas-txn-sender#7]
Apologies i’m not super familiar with rust. This seems like it’s a server component that accepts web requests and forwards transactions to the blockchain. Having a hard time figuring out what the API of this is like and how to interact with it.

Do you have a simple example of interfacing with this by chance? Is it like you serialize your transaction and send it to a particular port? Or am I misunderstanding entirely and this is more like a library component you would include in your own backend?

Thanks!

**Comment by vovkman** [comment]
It conforms to the solana rpc spec for sendTransaction! See [here](https://solana.com/docs/rpc/http/sendtransaction) for the spec
